config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pages#home"
  get "members" => "pages#members" # creates members_path
  get "contact" => "pages#contact" # creates contact_path
  get "research" => "pages#research"
  get "publications" => "pages#publications"
  get "pictures" => "pages#pictures"
  get "links" => "pages#links"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def links
  end

  def members
  end

  def publications
  end

  def research
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crispino Lab", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">About John<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Bio</a></li>
            <li class="divider"></li>
            <li><a href="#">CV</a></li>
            <!-- <li><a href=<"#">Separated link</a></li> -->
          </ul>
        </li>
        <li><%= link_to "Lab members", members_path %></li>
        <li><%= link_to "About our research", research_path %></li>
        <li><%= link_to "Recent publications", publications_path %></li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Other useful links", links_path %></li>
        <li><%= link_to "Contact us", contact_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crispino Lab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
  	<%= yield %>
	</div>	


</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>This is a working application created by Rahul Bhansali.  I've used the layout given by <%= link_to "One Month Rails","https://onemonthrails.com" %>, an incredibly helpful resource for learning Ruby on Rails.</p>

app/views/pages/contact.html.erb
<div class="page-header">
	<h1 class="text-center">Contact us</h1>
</div>
<address>
  <strong>Robert H Lurie Medical Research Center </strong><br>
  303 E Superior St, Room 5-250 <br>
 	Chicago, IL 60611<br>
  <abbr title="Phone">P:</abbr> (312) 503-1504
</address>

<address>
  <strong>John Crispino</strong><br>
  <a href="mailto:#">j-crispino@northwestern.edu</a>
</address>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1 class="text-center">Welcome to the Crispino Lab home page!</h1>
	<div class="top-buffer">
		<h5>Thanks for visiting our site, which is still under construction.  But soon, you'll be able to see our lab members and bios, information about our research, and other interesting things about what goes on in our lab!</h5>
	</div>
	
	<% if user_signed_in? %>
	<% else %>
			<div class="text-center">
				<div class="top-buffer">
					<h5><%= link_to "Lab members can sign in here", new_user_session_path, class: "btn btn-custom"%> <h2> or </h2><%= link_to "Sign up here", new_user_registration_path, class: "btn btn-custom"%></h5>
				</div>
			</div>
	<% end %>

<div class="container-fluid">
	<div class="row-fluid top-buffer">
    <div class="text-center">
    	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide="" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			    <div class="item active">
			      <img src="http://placehold.it/1200x400" class="img-responsive" alt="...">
			      <div class="carousel-caption">
    					<h3>Placeholder1</h3>
    					<h5>Placeholder1</h5>
			      </div>
			    </div>
			    <div class="item">
			      <img src="http://placehold.it/1200x400" class="img-responsive" alt="...">
			      <div class="carousel-caption">
    					<h3>Placeholder1</h3>
    					<h5>Placeholder1</h5>
			      </div>
			    </div>
			    <div class="item">
			      <img src="http://placehold.it/1200x400" class="img-responsive" alt="...">
			      <div class="carousel-caption">
    					<h3>Placeholder1</h3>
    					<h5>Placeholder1</h5>
			      </div>
			    </div>
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left"></span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right"></span>
			  </a>
			</div>
		</div>
	</div>
</div>

</div>

app/views/pages/links.html.erb
<h1>Related links:</h1>
<ul class="list-unstyled">
	  <h8 class="lead"> 
	  	<li> <%= link_to "American Society of Hematology", "http://www.hematology.org" %></li></h8>
	  <h8 class="lead"> 
	  	<li> <%= link_to "Samuel Waxman Cancer Research Foundation", "http://www.waxmancancer.org" %></li></h8>
	  <h8 class="lead"> 
	  	<li> <%= link_to "Ann & Robert H. Lurie Children's Hospital", "https://www.luriechildrens.org/" %></li></h8>
	  <h8 class="lead"> 
	  	<li> <%= link_to "Robert H. Lurie Comprehensive Cancer Center of Northwestern University", "http://www.cancer.northwestern.edu" %></li></h8>
	  <h8 class="lead"> 
	  	<li> <%= link_to "Northwestern Medicine", "http://www.northwesternmedicine.org/" %></li></h8>
	</ul>

<h1>Twitter feeds:</h1>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-lg-4">
			<div class="text-center">
				<h5 class="text-center">Ann & Robert H. Lurie Children's Hospital </h5>
				<a class="twitter-timeline", href="https://twitter.com/LurieChildrens" data-widget-id="469933072381517824">Tweets by @LurieChildrens</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="text-center">
				<h5>Robert H. Lurie Comprehensive Cancer Center</h5>
				<a class="twitter-timeline" href="https://twitter.com/LurieCancer" data-widget-id="469932942353903616">Tweets by @LurieCancer</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="text-center">
				<h5 class="text-center">Northwestern Medicine</h5>
				<a class="twitter-timeline" href="https://twitter.com/NMHnews" data-widget-id="469925500912025600">Tweets by @NMHnews</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
		</div>
	</div>	
</div>

app/views/pages/members.html.erb
<div class="page-header">
	<h1 class="text-center">Lab members</h1>
</div>

<div class="container-fluid">
 	<div class="row-fluid">
	    <div class="col-lg-3">
				<div class="btn-group btn-group-vertical">
					<div class="btn-group">
					  <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown"><small>Research Assistant Professors</small><span class="caret"></span>
				  	</button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="#">Gina Kirsammer, PhD</a></li>
					    <li class="divider"></li>
					    <li><a href="#">Qiang Jeremy Wen, MD, PhD</a></li>
					  </ul>
					</div>
					<div class="btn-group">
					  <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">Postdocs<span class="caret"></span>
				  	</button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="#">Ben Thompson, MD, PhD</a></li>
					    <li class="divider"></li>
					    <li><a href="#">Laure Gilles, PhD</a></li>
					    <li class="divider"></li>
					    <li><a href="#">Monika Stankiewicz, PhD</a></li>
					  </ul>
					</div>
					<div class="btn-group">
					   <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">Students<span class="caret"></span>
				  	</button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="#">Ben Goldenson, MSTP Candidate</a></li>
					  </ul>
					</div>
					<div class="btn-group">
					   <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">
				    Techs<span class="caret"></span>
				  	</button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="#">Rachael Schultz</a></li>
					    <li class="divider"></li>
					    <li><a href="#">Rahul Bhansali</a></li>
					    <li class="divider"></li>
					    <li><a href="#">Qiong Yang</a></li>
					  </ul>
					</div>
					<div class="btn-group">
					  <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">
				    Undergrads<span class="caret"></span>
				 	 	</button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="#">Ritika Rastogi</a></li>
					    <li class="divider"></li>
					    <li><a href="#">Virginia Curtis</a></li>
					  </ul>
					</div>
				</div>
			</div>
			<div class="col-lg-8 col-lg-pull-1">
				<!--Body content-->
				<div class="text-center">
					<h5>Choose from the left-hand toolbar to see labmember bios!</h5>
				</div>    
	    </div>
	</div>
	<div class="row-fluid">
		<div class="col-xs-6 col-md-4 col-lg-push-1">
    <a href="http://placehold.it/1200x400" class="thumbnail">
      <img data-src="holder.js/100%x180" class="img-responsive" alt="...">
    </a>
  </div>
</div>

app/views/pages/pictures.html.erb
<div class="page-header">
	<h1 class="text-center">Pictures around the lab!</h1>
</div>

<div class="container-fluid">
	<div class="row-fluid">
    <div class="text-center">
    	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide="" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			    <div class="item active">
			      <img src="http://placehold.it/1200x400" class="img-responsive" alt="...">
			      <div class="carousel-caption">
    					<h3>Placeholder1</h3>
    					<p>Placeholder1</p>
			      </div>
			    </div>
			    <div class="item">
			      <img src="http://placehold.it/1200x400" class="img-responsive" alt="...">
			      <div class="carousel-caption">
    					<h3>Placeholder1</h3>
    					<p>Placeholder1</p>
			      </div>
			    </div>
			    <div class="item">
			      <img src="http://placehold.it/1200x400" class="img-responsive" alt="...">
			      <div class="carousel-caption">
    					<h3>Placeholder1</h3>
    					<p>Placeholder1</p>
			      </div>
			    </div>
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left"></span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right"></span>
			  </a>
			</div>
		</div>
	</div>
</div>
      

app/views/pages/publications.html.erb
<div class="page-header">
	<h1 class="text-center">Recent publications</h1>
</div>	
	<ul class="list-unstyled">
	  <p class="lead"><li>Lane AA, Chapuy B, Lin CY, Tivey T, Li H, Townsend EC, van Bodegom D, Day TA, Wu SC, Liu H, Yoda A, Alexe G, Schinzel AC, Sullivan TJ, Malinge S, Taylor JE, Stegmaier K, Jaffe JD, Bustin M, Te Kronnie G, Izraeli S, Harris MH, Stevenson KE, Neuberg D, Silverman LB, Sallan SE, Bradner JE, Hahn WC, <strong>Crispino JD</strong>, Pellman D, Weinstock DM. Triplication of a 21q22 region contributes to B cell transformation through HMGN1 overexpression and loss of histone H3 Lys27 trimethylation. <em>Nat Genet</em>. 2014;46(6):618-23.</li></p>
	  <p class="lead"><li><strong>Crispino JD</strong>, Weiss MJ. Erythro-megakaryocytic transcription factors associated with hereditary anemia. <em>Blood</em>. 2014;123(20):3080-3088.</li></p>
	  <p class="lead"><li>Goldenson B, <strong>Crispino JD</strong>. The aurora kinases in cell cycle and leukemia. <em>Oncogene</em>. 2014; Advanced online publication.</li></p>
	  <p class="lead"><li>Liu L, Wen Q, Gong R, Gilles L, Stankiewicz MJ, Li W, Guo M, Li L, Sun X, Li W, <strong>Crispino JD</strong>, Huang Z. PSTPIP2 dysregulation contributes to aberrant terminal differentiation in GATA-1-deficient megakaryocytes by activating LYN. <em>Cell Death Dis</em>. 2014;5:e988.</li></p>
	  <p class="lead"><li>Krause DS, <strong>Crispino JD</strong>. Molecular pathways: induction of polyploidy as a novel differentiation therapy for leukemia. <em>Clin Cancer Res</em>. 2013;19(22):6084-8.</li></p>
	  <p class="lead"><li>Malinge S, Chlon T, Doré LC, Ketterling RP, Tallman MS, Paietta E, Gamis AS, Taub JW, Chou ST, Weiss MJ, <strong>Crispino JD</strong>, Figueroa ME. Development of acute megakaryoblastic leukemia in Down syndrome is associated with sequential epigenetic changes. <em>Blood</em>. 2013;122(14):e33-43.</li></p>
	  <p class="lead"><li>Lasho T, Johnson SH, Smith DI, <strong>Crispino JD, Pardanani A, Vasmatzis G, Tefferi A</strong>. Identification of submicroscopic genetic changes and precise breakpoint mapping in myelofibrosis using high resolution mate-pair sequencing. <em>Am J Hematol</em>. 2013;88(9):741-6.</li></p>
	  <p class="lead"><li>Khan I, Huang Z, Wen Q, Stankiewicz MJ, Gilles L, Goldenson B, Schultz R, Diebold L, Gurbuxani S, Finke CM, Lasho TL, Koppikar P, Pardanani A, Stein B, Altman JK, Levine RL, Tefferi A,<strong>Crispino JD</strong>. AKT is a therapeutic target in myeloproliferative neoplasms. <em>Leukemia</em>. 2013;27(9):1882-90.</li></p>
	  <p class="lead"><li>Birger Y, Goldberg L, Chlon TM, Goldenson B, Muler I, Schiby G, Jacob-Hirsch J, Rechavi G, <strong>Crispino JD</strong>, Izraeli S. Perturbation of fetal hematopoiesis in a mouse model of Down syndrome's transient myeloproliferative disorder. <em>Blood</em>. 2013;122(6):988-98.</li></p>
	  <p class="lead"><li>Stankiewicz MJ, <strong>Crispino JD</strong>. AKT collaborates with ERG and Gata1s to dysregulate megakaryopoiesis and promote AMKL. <em>Leukemia</em>. 2013;27(6):1339-47.</li></p>
	</ul>

	<h5 class="lead">For a full list of publications, visit our <%= link_to "PubMed", "http://www.ncbi.nlm.nih.gov/pubmed?term=Crispino%20JD%5BAuthor%5D&cauthor=true&cauthor_uid=24747640" %> page.</h5>

app/views/pages/research.html.erb
<div class="page-header">
	<h1 class="text-center">About our research</h1>
</div>

<div class="row-fluid">
	<h2><strong>Research Overview</strong></h4>
	<p class="lead">Research in the Crispino lab is focused on investigating the regulatory mechanisms governing normal and malignant blood cell development,with an emphasis on understanding the growth of erythroid cells (red blood cells) and megakaryocytes (platelet-producing cells). In addition, we are greatly interested in learning how changes in normal essential regulatorymolecules lead to human blood diseases, including leukemias, myelodysplastic syndromes (MDS) and myeloproliferative neoplasms (MPNs). Areas of major interest include:<p>

	<h5><strong>Mechanisms of leukemogenesis in children with Down syndrome:</strong></h5> 

	<p>Several years ago, we discovered that the zinc finger transcription factor GATA-1 is mutated in Acute Megakaryoblastic Leukemia(AMKL) in children with Down syndrome (DS). We further found that GATA1 mutations are also present in apre-leukemia, named transient myeloproliferative disorder, which is relatively common in infants with Down syndrome. Current studies in the lab are focused on characterizing the role of GATA-1 in normal megakaryocyte development and on investigating how GATA1 mutations contribute to leukemia. In related experiments, we are also studying the mechanisms by which trisomy 21 promotes the development of leukemia. Our long-term goal isto unravel the mystery of why children with DS are predisposed to leukemia. These studies are performed in collaboration with physicians at Ann & Robert H. Lurie Children’s Hospital of Chicago and the Children’s Oncology Group. In addition to studying mouse models of Down syndrome, we are now harnessing the power of induced pluripotent stem (iPS) cells to define the role of trisomy 21 in leukemia. Incollaboration with Drs. Vasil Galat and Marcelo (Bento) Soares at Stanley Manne Children's Research Institute, we are comparing gene expression and methylationprofiles of iPS cells derived from euploid and trisomic human cells.</p>

 	<h5><strong>Regulation of megakaryocyte proliferation, polyploidization and terminal maturation:</strong></h5>  
	<p>Megakaryocytes, the precursors to platelets, are one of the few cells types to undergo polyploidization in the normal course of maturation.We are using high throughput methods to identify genes that control the switch between the proliferative and the endomitotic cell cycle, such as survivin. Inaddition, we are examining the contribution of key transcription factors, suchas GATA-1, GATA-2 and Ets proteins in the regulation of megakaryocyte geneexpression, terminal differentiation and lineage commitment.</p>

 	<h5><strong>Development of novel therapeutics for human megakaryocytic neoplasms:</h5></strong>

	<p>In an ongoing collaboration with the Broad Institute, wehave identified a set of small molecules that rapidly and robustly induceproliferation arrest and terminal maturation of malignant megakaryocytes, including those that harbor mutations in GATA1,JAK3, or c-MPL, as well as thosethat express the t(1;22) fusion protein associated with pediatric non-DS AMKL.These small molecules induce features of megakaryocyte differentiation,including extensive polyploidization and expression of markers of terminaldifferentiation, but they do not appear to promote platelet release. We are currently developing these compounds as potential new therapies for blood disorders, including acute megakaryocytic leukemia and primary myelofibrosis.</p> 

	 <h5><strong>Control of red blood cells development:</h5></strong> 

	<p>Survivin, a member of the inhibitor of apoptosis (IAP) family that also plays an essential role in cytokinesis, is differentially expressed during erythroid versus megakaryocyte development. We recently reported that survivin is required for the maintenance of hematopoietic stemand progenitor cells as well as for red blood cell development. More recently,we have found that survivin is highly expressed in post-mitotic erythroblasts.We are currently studying the contribution of survivin to terminal maturation of erythroid cells, including enucleation.</p>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= pin.user.try(:email) %> <!--Or use <%= pin.user.email if pin.user %> --></td> 
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form'%>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<h5 id="notice"><%= notice %></h5>

<h5>
  <strong>Description:</strong>
  <%= @pin.description %>
</h5>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>